<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Me Science - Wijsheid over innerlijk welbevinding</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="Keywords" content="Oracle Science Wellbeing Happiness Question">
    <meta name="Description" content="Wisdom about wellbeing">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="view/css/style.css">
    <link href='https://fonts.googleapis.com/css?family=Source%20Code%20Pro' rel='stylesheet'>
</head>
<body>
    <header>
    </header>
    <main>
    </main>
</body>
</html>
