<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Me Science - Wijsheid over innerlijk welbevinding</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="Keywords" content="Oracle Science Wellbeing Happiness Question">
    <meta name="Description" content="Wisdom about wellbeing">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="view/css/style.css">
    <link href='https://fonts.googleapis.com/css?family=Source%20Code%20Pro' rel='stylesheet'>
</head>
<body>
    <header>
        <hr>
        <h1>Wijsheid over jezelf</h1>
        <h2>Speel met wijze mensen</h2>
    </header>
    <main>
        <hr>
        <h3>Kies je eigen gids</h3>
        <ul>
            <?php
            foreach( $this->guides as $id => $credentials )
            {
                if ( array_key_exists( "name", $credentials ) )
                {
                    $name = $credentials[ "name" ];
                }
                else
                {
                    $name = ucfirst( $id );
                }

                if ( array_key_exists( "birth", $credentials ) )
                {
                    $birth = $credentials[ "birth" ];
                }
                else
                {
                    $birth = "?";
                }

                if ( array_key_exists( "death", $credentials ) )
                {
                    $death = $credentials[ "death" ];
                }
                else
                {
                    $death = "?";
                }
                $life = '<span>( ' . $birth . ' - ' . $death . ' )</span>';

                if ( array_key_exists( "wikipedia", $credentials ) )
                {
                    $wikipedia = '<a href="'. $credentials[ "wikipedia" ] . '" target="blank"><img style="height:28px;" src="https://upload.wikimedia.org/wikipedia/commons/f/f6/Wikipedia-logo-v2-wordmark.svg"></a>';
                }
                else
                {
                    $wikipedia = "";
                }
                $life = '<span>( ' . $birth . ' - ' . $death . ' )</span>';

                if ( array_key_exists( "game", $credentials ) )
                {
                    $item = '<a class="mescience" href="' . $credentials[ "game" ] . '.php">' . $name . '</a>';
                }
                else
                {
                    $item = $name;
                }

                echo '            <li>' . $item . ' <i class="mescience_date">' . $life . '</i>' . $wikipedia . '</li>';
            }
            ?>
        </ul>
    </main>
</body>
</html>
